name: CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - labeled
      - unlabeled

# Restrict jobs in this workflow to only be allowed to read this repo by default.
#
# If you are wanting to introduce a job/tool that requires more permissions (such
# as posting comments or commits to the repository), then you should grant just
# that job the necessarily permissions by giving it a dedicated `permissions` block.
permissions: {}
#permissions:
#  contents: read # to fetch code (actions/checkout)
#  pull-requests: write

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  do_stuff:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: mshick/add-pr-comment@v1
        if: github.event_name == 'pull_request' && github.event.action == 'labeled'
        with:
          message: You added the "${{ github.event.label.name }}" label!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
      - uses: mshick/add-pr-comment@v1
        if: github.event_name == 'pull_request' && github.event.action == 'unlabeled'
        with:
          message: You removed the "${{ github.event.label.name }}" label!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
  cleanup_mdev:
    if: |
      github.event_name == 'pull_request' && (
        (github.event.action == 'unlabeled' && github.event.label.name == 'documentation') ||
        (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'documentation'))
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Cleaning up documentation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
  run_action:
    uses: ./.github/workflows/trigger.yml
    permissions: {}
