name: matrix-test
on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        exit_code: [0, 1]
    steps:
#      - run: exit ${{ matrix.exit_code }}
      - run: exit 0
  after:
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - run: echo 'hello world'
